name: Docs
on:
  pull_request:
    branches:
      - main
      -
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "publish to pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install .[docs]

      - name: Show versions
        run: pip freeze

      - name: Build Docs
        run: python docs/make.py

      - name: Upload site as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/build/html
          retention-days: 14
